function ResearchResults({
  result,
  onNewResearch,
}) {
  const research = result.company_research;
  const analysis = result.sales_analysis;
  const outreach = result.outreach;

  return (
    <section className="results-section">
      <div className="results-header">
        <div>
          <p className="eyebrow">RESEARCH COMPLETE</p>

          <h1>{research.company_name}</h1>

          <p>
            Company intelligence generated by IntelliReach.
          </p>
        </div>

        <button
          className="secondary-button"
          onClick={onNewResearch}
        >
          ← New Research
        </button>
      </div>

      <div className="results-grid">
        <article className="result-card overview-card">
          <div className="card-label">
            COMPANY OVERVIEW
          </div>

          <h2>What they do</h2>

          <p>{research.overview}</p>

          <div className="detail-block">
            <h3>Products & Services</h3>

            <ul>
              {research.products_services.map(
                (item, index) => (
                  <li key={index}>{item}</li>
                )
              )}
            </ul>
          </div>

          <div className="detail-block">
            <h3>Target Market</h3>

            <p>{research.target_market}</p>
          </div>
        </article>

        <article className="result-card">
          <div className="card-label">
            RECENT DEVELOPMENTS
          </div>

          <h2>What's happening</h2>

          <ul className="result-list">
            {research.recent_developments.map(
              (item, index) => (
                <li key={index}>{item}</li>
              )
            )}
          </ul>
        </article>

        <article className="result-card">
          <div className="card-label">
            TECHNOLOGY SIGNALS
          </div>

          <h2>Technology & AI</h2>

          <ul className="result-list">
            {research.technology_signals.map(
              (item, index) => (
                <li key={index}>{item}</li>
              )
            )}
          </ul>
        </article>

        <article className="result-card pain-points-card">
          <div className="card-label">
            SALES INTELLIGENCE
          </div>

          <h2>Potential Pain Points</h2>

          <div className="pain-point-list">
            {analysis.pain_points.map(
              (item, index) => (
                <div
                  className="pain-point"
                  key={index}
                >
                  <span>
                    {String(index + 1).padStart(2, "0")}
                  </span>

                  <p>{item}</p>
                </div>
              )
            )}
          </div>
        </article>

        <article className="result-card opportunity-card">
          <div className="card-label">
            STRONGEST OPPORTUNITY
          </div>

          <h2>
            {analysis.strongest_opportunity}
          </h2>

          <p>{analysis.business_value}</p>

          <div className="hook">
            <span>OUTREACH HOOK</span>

            <p>{analysis.outreach_hook}</p>
          </div>
        </article>

        <article className="result-card outreach-card">
          <div className="card-label">
            PERSONALIZED OUTREACH
          </div>

          <h2>Ready to send</h2>

          <div className="email-box">
            {outreach.email}
          </div>

          <div className="detail-block">
            <h3>Call Talking Points</h3>

            <ol>
              {outreach.talking_points.map(
                (item, index) => (
                  <li key={index}>{item}</li>
                )
              )}
            </ol>
          </div>
        </article>
      </div>
    </section>
  );
}

export default ResearchResults;