import { useState } from "react";

function ResearchResults({
  result,
  onNewResearch,
}) {
  const [copied, setCopied] = useState(false);

  const research = result.company_research;
  const analysis = result.sales_analysis;
  const outreach = result.outreach;

  const handleCopyEmail = async () => {
    try {
      await navigator.clipboard.writeText(
        outreach.email
      );

      setCopied(true);

      setTimeout(() => {
        setCopied(false);
      }, 2000);
    } catch (error) {
      console.error(
        "Failed to copy email:",
        error
      );
    }
  };

  return (
    <section className="results-section">
      {/* -------------------------------------------------
          RESULTS HEADER
      ------------------------------------------------- */}

      <div className="results-header">
        <div className="results-title-group">
          <div className="results-status">
            <span className="results-status-dot"></span>
            RESEARCH COMPLETE
          </div>

          <h1>{research.company_name}</h1>

          <p>
            Company intelligence generated by
            IntelliReach.
          </p>
        </div>

        <button
          className="secondary-button"
          onClick={onNewResearch}
        >
          <span>←</span>
          New Research
        </button>
      </div>

      {/* -------------------------------------------------
          RESULTS GRID
      ------------------------------------------------- */}

      <div className="results-grid">

        {/* COMPANY OVERVIEW */}

        <article className="result-card overview-card">
          <div className="card-label">
            COMPANY OVERVIEW
          </div>

          <h2>What they do</h2>

          <p>{research.overview}</p>

          <div className="detail-block">
            <h3>Products & Services</h3>

            <ul>
              {research.products_services.map(
                (item, index) => (
                  <li key={index}>
                    {item}
                  </li>
                )
              )}
            </ul>
          </div>

          <div className="detail-block">
            <h3>Target Market</h3>

            <p>
              {research.target_market}
            </p>
          </div>
        </article>


        {/* RECENT DEVELOPMENTS */}

        <article className="result-card">
          <div className="card-label">
            RECENT DEVELOPMENTS
          </div>

          <h2>What's happening</h2>

          <ul className="result-list">
            {research.recent_developments.map(
              (item, index) => (
                <li key={index}>
                  {item}
                </li>
              )
            )}
          </ul>
        </article>


        {/* TECHNOLOGY SIGNALS */}

        <article className="result-card">
          <div className="card-label">
            TECHNOLOGY SIGNALS
          </div>

          <h2>Technology & AI</h2>

          <ul className="result-list">
            {research.technology_signals.map(
              (item, index) => (
                <li key={index}>
                  {item}
                </li>
              )
            )}
          </ul>
        </article>


        {/* PAIN POINTS */}

        <article className="result-card pain-points-card">
          <div className="card-label">
            SALES INTELLIGENCE
          </div>

          <h2>Potential Pain Points</h2>

          <p className="card-subtitle">
            Areas where the researched company may
            have operational or growth opportunities.
          </p>

          <div className="pain-point-list">
            {analysis.pain_points.map(
              (item, index) => (
                <div
                  className="pain-point"
                  key={index}
                >
                  <span className="pain-point-number">
                    {String(index + 1).padStart(
                      2,
                      "0"
                    )}
                  </span>

                  <p>{item}</p>
                </div>
              )
            )}
          </div>
        </article>


        {/* STRONGEST OPPORTUNITY */}

        <article className="result-card opportunity-card">
          <div className="opportunity-heading">
            <div className="card-label">
              STRONGEST OPPORTUNITY
            </div>

            <span className="opportunity-badge">
              AI INSIGHT
            </span>
          </div>

          <h2>
            {analysis.strongest_opportunity}
          </h2>

          <div className="business-value">
            <span>BUSINESS VALUE</span>

            <p>
              {analysis.business_value}
            </p>
          </div>

          <div className="hook">
            <span>OUTREACH HOOK</span>

            <p>
              {analysis.outreach_hook}
            </p>
          </div>
        </article>


        {/* PERSONALIZED OUTREACH */}

        <article className="result-card outreach-card">
          <div className="outreach-header">
            <div>
              <div className="card-label">
                PERSONALIZED OUTREACH
              </div>

              <h2>Ready to send</h2>
            </div>

            <button
              type="button"
              className="copy-email-button"
              onClick={handleCopyEmail}
            >
              {copied ? (
                <>
                  <span>✓</span>
                  Copied
                </>
              ) : (
                <>
                  <span>⧉</span>
                  Copy Email
                </>
              )}
            </button>
          </div>


          {/* EMAIL PREVIEW */}

          <div className="email-preview">
            <div className="email-preview-bar">
              <span></span>
              <span></span>
              <span></span>
            </div>

            <div className="email-box">
              {outreach.email}
            </div>
          </div>


          {/* TALKING POINTS */}

          <div className="detail-block talking-points">
            <h3>
              Call Talking Points
            </h3>

            <ol>
              {outreach.talking_points.map(
                (item, index) => (
                  <li key={index}>
                    <span>
                      {String(index + 1).padStart(
                        2,
                        "0"
                      )}
                    </span>

                    <p>{item}</p>
                  </li>
                )
              )}
            </ol>
          </div>
        </article>

      </div>
    </section>
  );
}

export default ResearchResults;